// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/threat.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // ex: "1.2.3.4" ou Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_threat_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exists          bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ThreatType      string                 `protobuf:"bytes,2,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`                 // ex: "critical_malware" (agregado)
	ConfidenceScore int32                  `protobuf:"varint,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 0-100 (Score calculado/máximo)
	ActionBlock     bool                   `protobuf:"varint,4,opt,name=action_block,json=actionBlock,proto3" json:"action_block,omitempty"`             // Sugestão explícita de ação (facilita pro WAF)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_threat_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckResponse) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *CheckResponse) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *CheckResponse) GetActionBlock() bool {
	if x != nil {
		return x.ActionBlock
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_threat_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IOCDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "ip", "domain", "hash"
	OverallScore  int32                  `protobuf:"varint,3,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	AllTags       []string               `protobuf:"bytes,4,rep,name=all_tags,json=allTags,proto3" json:"all_tags,omitempty"` // ["botnet", "win32", "apt29"]
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Sightings     []*Sighting            `protobuf:"bytes,7,rep,name=sightings,proto3" json:"sightings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOCDetails) Reset() {
	*x = IOCDetails{}
	mi := &file_proto_threat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOCDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOCDetails) ProtoMessage() {}

func (x *IOCDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_threat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOCDetails.ProtoReflect.Descriptor instead.
func (*IOCDetails) Descriptor() ([]byte, []int) {
	return file_proto_threat_proto_rawDescGZIP(), []int{3}
}

func (x *IOCDetails) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IOCDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IOCDetails) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *IOCDetails) GetAllTags() []string {
	if x != nil {
		return x.AllTags
	}
	return nil
}

func (x *IOCDetails) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *IOCDetails) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *IOCDetails) GetSightings() []*Sighting {
	if x != nil {
		return x.Sightings
	}
	return nil
}

type Sighting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                                 // "abusech-urlhaus"
	ExternalLink  string                 `protobuf:"bytes,2,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"` // Link para o reporte original
	ThreatType    string                 `protobuf:"bytes,3,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	DateIngested  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_ingested,json=dateIngested,proto3" json:"date_ingested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sighting) Reset() {
	*x = Sighting{}
	mi := &file_proto_threat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sighting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sighting) ProtoMessage() {}

func (x *Sighting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_threat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sighting.ProtoReflect.Descriptor instead.
func (*Sighting) Descriptor() ([]byte, []int) {
	return file_proto_threat_proto_rawDescGZIP(), []int{4}
}

func (x *Sighting) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Sighting) GetExternalLink() string {
	if x != nil {
		return x.ExternalLink
	}
	return ""
}

func (x *Sighting) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *Sighting) GetDateIngested() *timestamppb.Timestamp {
	if x != nil {
		return x.DateIngested
	}
	return nil
}

var File_proto_threat_proto protoreflect.FileDescriptor

const file_proto_threat_proto_rawDesc = "" +
	"\n" +
	"\x12proto/threat.proto\x12\n" +
	"watchtower\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\fCheckRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x96\x01\n" +
	"\rCheckResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vthreat_type\x18\x02 \x01(\tR\n" +
	"threatType\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x05R\x0fconfidenceScore\x12!\n" +
	"\faction_block\x18\x04 \x01(\bR\vactionBlock\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x9e\x02\n" +
	"\n" +
	"IOCDetails\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\roverall_score\x18\x03 \x01(\x05R\foverallScore\x12\x19\n" +
	"\ball_tags\x18\x04 \x03(\tR\aallTags\x129\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x122\n" +
	"\tsightings\x18\a \x03(\v2\x14.watchtower.SightingR\tsightings\"\xa9\x01\n" +
	"\bSighting\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12#\n" +
	"\rexternal_link\x18\x02 \x01(\tR\fexternalLink\x12\x1f\n" +
	"\vthreat_type\x18\x03 \x01(\tR\n" +
	"threatType\x12?\n" +
	"\rdate_ingested\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fdateIngested2\x8d\x01\n" +
	"\n" +
	"Watchtower\x12?\n" +
	"\bCheckIOC\x12\x18.watchtower.CheckRequest\x1a\x19.watchtower.CheckResponse\x12>\n" +
	"\tSearchIOC\x12\x19.watchtower.SearchRequest\x1a\x16.watchtower.IOCDetailsB0Z.github.com/hive-corporation/watchtower/pkg/apib\x06proto3"

var (
	file_proto_threat_proto_rawDescOnce sync.Once
	file_proto_threat_proto_rawDescData []byte
)

func file_proto_threat_proto_rawDescGZIP() []byte {
	file_proto_threat_proto_rawDescOnce.Do(func() {
		// #nosec G103 -- This is auto-generated protobuf code, unsafe usage is required
		file_proto_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_threat_proto_rawDesc), len(file_proto_threat_proto_rawDesc)))
	})
	return file_proto_threat_proto_rawDescData
}

var file_proto_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_threat_proto_goTypes = []any{
	(*CheckRequest)(nil),          // 0: watchtower.CheckRequest
	(*CheckResponse)(nil),         // 1: watchtower.CheckResponse
	(*SearchRequest)(nil),         // 2: watchtower.SearchRequest
	(*IOCDetails)(nil),            // 3: watchtower.IOCDetails
	(*Sighting)(nil),              // 4: watchtower.Sighting
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_threat_proto_depIdxs = []int32{
	5, // 0: watchtower.IOCDetails.first_seen:type_name -> google.protobuf.Timestamp
	5, // 1: watchtower.IOCDetails.last_seen:type_name -> google.protobuf.Timestamp
	4, // 2: watchtower.IOCDetails.sightings:type_name -> watchtower.Sighting
	5, // 3: watchtower.Sighting.date_ingested:type_name -> google.protobuf.Timestamp
	0, // 4: watchtower.Watchtower.CheckIOC:input_type -> watchtower.CheckRequest
	2, // 5: watchtower.Watchtower.SearchIOC:input_type -> watchtower.SearchRequest
	1, // 6: watchtower.Watchtower.CheckIOC:output_type -> watchtower.CheckResponse
	3, // 7: watchtower.Watchtower.SearchIOC:output_type -> watchtower.IOCDetails
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_threat_proto_init() }
func file_proto_threat_proto_init() {
	if File_proto_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			// #nosec G103 -- This is auto-generated protobuf code, unsafe usage is required
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_threat_proto_rawDesc), len(file_proto_threat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_threat_proto_goTypes,
		DependencyIndexes: file_proto_threat_proto_depIdxs,
		MessageInfos:      file_proto_threat_proto_msgTypes,
	}.Build()
	File_proto_threat_proto = out.File
	file_proto_threat_proto_goTypes = nil
	file_proto_threat_proto_depIdxs = nil
}
