// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/threat.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Watchtower_CheckIOC_FullMethodName  = "/watchtower.Watchtower/CheckIOC"
	Watchtower_SearchIOC_FullMethodName = "/watchtower.Watchtower/SearchIOC"
)

// WatchtowerClient is the client API for Watchtower service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchtowerClient interface {
	CheckIOC(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	SearchIOC(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*IOCDetails, error)
}

type watchtowerClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchtowerClient(cc grpc.ClientConnInterface) WatchtowerClient {
	return &watchtowerClient{cc}
}

func (c *watchtowerClient) CheckIOC(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, Watchtower_CheckIOC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchtowerClient) SearchIOC(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*IOCDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IOCDetails)
	err := c.cc.Invoke(ctx, Watchtower_SearchIOC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchtowerServer is the server API for Watchtower service.
// All implementations must embed UnimplementedWatchtowerServer
// for forward compatibility.
type WatchtowerServer interface {
	CheckIOC(context.Context, *CheckRequest) (*CheckResponse, error)
	SearchIOC(context.Context, *SearchRequest) (*IOCDetails, error)
	mustEmbedUnimplementedWatchtowerServer()
}

// UnimplementedWatchtowerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchtowerServer struct{}

func (UnimplementedWatchtowerServer) CheckIOC(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIOC not implemented")
}
func (UnimplementedWatchtowerServer) SearchIOC(context.Context, *SearchRequest) (*IOCDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchIOC not implemented")
}
func (UnimplementedWatchtowerServer) mustEmbedUnimplementedWatchtowerServer() {}
func (UnimplementedWatchtowerServer) testEmbeddedByValue()                    {}

// UnsafeWatchtowerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchtowerServer will
// result in compilation errors.
type UnsafeWatchtowerServer interface {
	mustEmbedUnimplementedWatchtowerServer()
}

func RegisterWatchtowerServer(s grpc.ServiceRegistrar, srv WatchtowerServer) {
	// If the following call panics, it indicates UnimplementedWatchtowerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Watchtower_ServiceDesc, srv)
}

func _Watchtower_CheckIOC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchtowerServer).CheckIOC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchtower_CheckIOC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchtowerServer).CheckIOC(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watchtower_SearchIOC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchtowerServer).SearchIOC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchtower_SearchIOC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchtowerServer).SearchIOC(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Watchtower_ServiceDesc is the grpc.ServiceDesc for Watchtower service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watchtower_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchtower.Watchtower",
	HandlerType: (*WatchtowerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIOC",
			Handler:    _Watchtower_CheckIOC_Handler,
		},
		{
			MethodName: "SearchIOC",
			Handler:    _Watchtower_SearchIOC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/threat.proto",
}
